version: '3.3'
services:
    sonarr:
        container_name: sonarr
        ports:
            - '8989:8989'
        volumes:
            - 'sonarr_data:/config'
            - '/srv/share/media/videos/tv:/tv'
            - '/srv/share/downloads:/downloads'
            - '/etc/localtime:/etc/localtime:ro'
        environment:
            - TZ=America/New_York
            - PGID=1000
            - PUID=1000
            - UMASK_SET=002
        restart: unless-stopped
        network_mode: bridge_media
        image: linuxserver/sonarr
