version: '3.3'
services:
    pms-docker:
        container_name: plex
        ports:
            - '32400:32400/tcp'
            - '8324:8324/tcp'
            - '32469:32469/tcp'
            - '1900:1900/udp'
            - '32410:32410/udp'
            - '32412:32412/udp'
            - '32413:32413/udp'
            - '32414:32414/udp'
        environment:
            - TZ=<timezone>
            - PLEX_CLAIM=<claimToken>
            - 'ADVERTISE_IP=http://<hostIPAddress>:32400/'
        hostname: '<HOSTNAME>'
        volumes:
            - '<path/to/plex/database>:/config'
            - '<path/to/transcode/temp>:/transcode'
            - '<path/to/media>:/data'
        image: plexinc/pms-docker
