version: '3.3'
services:
    portainer:
        container_name: portainer
        ports:
            - '9000:9000'
        volumes:
            - 'portainer_data:/data'
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/etc/localtime:/etc/localtime:ro'
        environment:
            - TZ=America/New_York
            - PGID=1000
            - PUID=1000
            - UMASK_SET=002
        restart: always
        network_mode: bridge_all
        image: portainer/portainer-ce
